### ISSUE TITLE
Assertion failure in do_work in StopMutators

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#379]
Run the following command on x64, Linux, OpenJDK with GDB

```sh
env RUST_BACKTRACE=1 MMTK_MIN_NURSERY=524288 MMTK_MAX_NURSERY=524288 MMTK_PLAN=GenCopy RUST_LOG=info gdb --args /home/wks/projects/mmtk-github/mmtk-openjdk/repos/openjdk/build/linux-x86_64-normal-server-slowdebug/jdk/bin/java -XX:+UseThirdPartyHeap -Xms512M -Xmx512M -jar ./dacapo-9.12-MR1-bach.jar lusearch
```

In GDB, execute the following commands:

```
handle SIGSEGV noprint nostop
run
```

and there is a high chance to get an assertion failure:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/gc_work.rs:196:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/6a758ea7e48416b968955535094479dc2e7cc9e1/library/core/src/panicking.rs:117:5
   4: <mmtk::scheduler::gc_work::StopMutators<E> as mmtk::scheduler::work::GCWork<<E as mmtk::scheduler::gc_work::ProcessEdgesWork>::VM>>::do_work
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/gc_work.rs:196:13
   5: <W as mmtk::scheduler::work::Work<mmtk::mmtk::MMTK<VM>>>::do_work
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/work.rs:34:9
   6: mmtk::scheduler::work::Work::do_work_with_stat
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/work.rs:14:9
   7: mmtk::scheduler::scheduler::Scheduler<C>::process_coordinator_work
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/scheduler.rs:201:9
   8: mmtk::scheduler::scheduler::Scheduler<C>::wait_for_completion
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/scheduler.rs:214:21
   9: mmtk::plan::controller_collector_context::ControllerCollectorContext<VM>::run
             at /home/wks/projects/mmtk-github/mmtk-core/src/plan/controller_collector_context.rs:67:13
  10: mmtk::memory_manager::start_control_collector
             at /home/wks/projects/mmtk-github/mmtk-core/src/memory_manager.rs:36:5
  11: start_control_collector
             at /home/wks/projects/mmtk-github/mmtk-openjdk/mmtk/src/api.rs:54:5
  12: _ZN17MMTkContextThread3runEv
  13: _ZN6Thread8call_runEv
  14: _ZL19thread_native_entryP6Thread
  15: start_thread
  16: __GI___clone
```

When not using GDB, there is chance that the process will hang for a long time before exiting normally (probably triggering a different bug).

**Comment by k-sareen** [comment]
I had encountered this earlier (for SemiSpace) and I thought I had fixed it: can you try using `SeqCst` [here](https://github.com/mmtk/mmtk-core/blob/2b55f89622dcc4c293bb472c634165e2ce7c2c5c/src/scheduler/gc_work.rs#L322) to see if that potentially fixes the issue? `Release` might be too weak.

**Comment by wks** [comment]
No. I changed the memory order for success to `SeqCst`, and the same assertion failure can still be reproduced.

I sometimes find that `<E::VM as VMBinding>::VMActivePlan::number_of_mutators();` may return a number that is smaller than the actual number of mutators that shall be scanned.  For example, in one execution, `number_of_mutators()` returned 24, but 25 mutators are scanned, that is, `scanned_stacks` is incremented 25 times.

**Comment by k-sareen** [comment]
On the flip side, it could be that the there is some issue with the ScanStacks code that makes it scan `number_of_mutators() + 1` stacks. I'm not 100% sure where the issue is coming from

**Comment by wks** [comment]
I printed more logs and found that during the last GC, one GC worker scanned the same mutator twice.  Here is a log:

```
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW:coord] stop_all_mutators start
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW:coord] stop_all_mutators end
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940011a0] [mutator:0x7ffff00312e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001ef0] [mutator:0x7ffff03bc2e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940011a0] [mutator:0x7ffff00312e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002670] [mutator:0x7ffff08672e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001ef0] [mutator:0x7ffff03bc2e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002750] [mutator:0x7ffff087dae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002670] [mutator:0x7ffff08672e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940023d0] [mutator:0x7ffff087b2e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001ef0] [mutator:0x7ffff03bc2e8] old scanned_stacks = 0, new scanned_stacks = 1
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002750] [mutator:0x7ffff087dae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940023d0] [mutator:0x7ffff087b2e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001490] [mutator:0x7ffff08712e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001df0] [mutator:0x7ffff0878ae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940020a0] [mutator:0x7ffff0873ae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001620] [mutator:0x7ffff08762e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001490] [mutator:0x7ffff08712e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001df0] [mutator:0x7ffff0878ae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940020a0] [mutator:0x7ffff0873ae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001620] [mutator:0x7ffff08762e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940026f0] [mutator:0x7ffff086e2e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002750] [mutator:0x7ffff087dae8] old scanned_stacks = 1, new scanned_stacks = 2
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940020a0] [mutator:0x7ffff0873ae8] old scanned_stacks = 3, new scanned_stacks = 4
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940026f0] [mutator:0x7ffff086e2e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001620] [mutator:0x7ffff08762e8] old scanned_stacks = 4, new scanned_stacks = 5
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002670] [mutator:0x7ffff08672e8] old scanned_stacks = 2, new scanned_stacks = 3
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940011a0] [mutator:0x7ffff00312e8] old scanned_stacks = 6, new scanned_stacks = 7
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940026d0] [mutator:0x7ffff08632e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940010f0] [mutator:0x7ffff0434ae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001360] [mutator:0x7ffff03c6ae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002710] [mutator:0x7ffff086bae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940010f0] [mutator:0x7ffff0434ae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002080] [mutator:0x7ffff08652e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001360] [mutator:0x7ffff03c6ae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940023d0] [mutator:0x7ffff087b2e8] old scanned_stacks = 7, new scanned_stacks = 8
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001490] [mutator:0x7ffff08712e8] old scanned_stacks = 5, new scanned_stacks = 6
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002080] [mutator:0x7ffff08652e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940026d0] [mutator:0x7ffff08632e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001360] [mutator:0x7ffff03c6ae8] old scanned_stacks = 9, new scanned_stacks = 10
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002450] [mutator:0x7ffff03c42e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940024b0] [mutator:0x7ffff03c1ae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002710] [mutator:0x7ffff086bae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940025f0] [mutator:0x7ffff03beae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001df0] [mutator:0x7ffff0878ae8] old scanned_stacks = 8, new scanned_stacks = 9
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940018b0] [mutator:0x7ffff039cae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940025f0] [mutator:0x7ffff03beae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002450] [mutator:0x7ffff03c42e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940024b0] [mutator:0x7ffff03c1ae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002570] [mutator:0x7ffff0379ae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940018b0] [mutator:0x7ffff039cae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002450] [mutator:0x7ffff03c42e8] old scanned_stacks = 10, new scanned_stacks = 11
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001e10] [mutator:0x7ffff0869ae8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002570] [mutator:0x7ffff0379ae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940024b0] [mutator:0x7ffff03c1ae8] old scanned_stacks = 11, new scanned_stacks = 12
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fffd00011b0] [mutator:0x7ffff086e2e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940018b0] [mutator:0x7ffff039cae8] old scanned_stacks = 12, new scanned_stacks = 13
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001e10] [mutator:0x7ffff0869ae8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002630] [mutator:0x7ffff03772e8] ScanStackRoot begin
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fffd00011b0] [mutator:0x7ffff086e2e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940025f0] [mutator:0x7ffff03beae8] old scanned_stacks = 13, new scanned_stacks = 14
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002630] [mutator:0x7ffff03772e8] I see mutaturs = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940010f0] [mutator:0x7ffff0434ae8] old scanned_stacks = 14, new scanned_stacks = 15
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002570] [mutator:0x7ffff0379ae8] old scanned_stacks = 15, new scanned_stacks = 16
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002630] [mutator:0x7ffff03772e8] old scanned_stacks = 16, new scanned_stacks = 17
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002710] [mutator:0x7ffff086bae8] old scanned_stacks = 17, new scanned_stacks = 18
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940026f0] [mutator:0x7ffff086e2e8] old scanned_stacks = 18, new scanned_stacks = 19
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94002080] [mutator:0x7ffff08652e8] old scanned_stacks = 19, new scanned_stacks = 20
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff940026d0] [mutator:0x7ffff08632e8] old scanned_stacks = 20, new scanned_stacks = 21
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001e10] [mutator:0x7ffff0869ae8] old scanned_stacks = 21, new scanned_stacks = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001e10] [mutator:0x7ffff0869ae8] current = 22, mutators = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001e10] [mutator:0x7ffff0869ae8] attempt to cmpxchg 22 to 0
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fff94001e10] [mutator:0x7ffff0869ae8] cmpxchg successful old scanned_stacks = 22, new scanned_stacks = 0, number_of_mutators = 22
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] [STW] [worker:0x7fffd00011b0] [mutator:0x7ffff086e2e8] old scanned_stacks = 0, new scanned_stacks = 1
[2021-07-19T03:56:12Z INFO  mmtk::scheduler::gc_work] End of GC
```

Note that mutator `0x7ffff086e2e8` is processed by two different workers, namely `0x7fffd00011b0` and `0x7fff940026f0`.

**Comment by k-sareen** [comment]
Okay so seems like I was right -- for some reason we scan `number_of_mutators() + 1` times. I can't say I'm too familiar with the root scanning code, but is this perchance an OpenJDK bug wherein we accidentally make an extra `ScanStackRoot` work packet?

**Comment by wks** [comment]
So I added a log to `openjdk/mmtk/src/collections.rs:create_mutator_scan_work`.  You are right.  When that bug occurs, this function is called twice for a mutator.  More interestingly, that mutator is always the first mutator passed to `create_mutator_scan_work` in one STW.

**Comment by k-sareen** [comment]
Hmm -- yep that was the function I was looking at as well. Other than `stop_all_mutators()` I can't see where the `create_mutator_scan_work()` function is used. Seems like a potential race condition in the binding then?

**Comment by k-sareen** [comment]
Seems like `create_stack_scan_work()` can be called by `report_java_thread_yield` in `openjdk/mmtkHeap.cpp:503`. This function seems to be used in the safepoint code for our OpenJDK fork at `src/hotspot/share/runtime/safepoint.cpp:297`.

**Comment by wks** [comment]
I found `SafepointSynchronize::begin()` called twice after one `stop_all_mutators()` call.

**Comment by k-sareen** [comment]
Aha. So it is related to the `report_java_thread_yield()`. Should we add a guard somewhere? As a hack, we could keep track of the first mutator reference in `create_mutator_scan_work()` and only create the `ScanStackRoot` work packet if it's not equal to the first mutator. We then reset at mutator reference in `mmtk_resume_mutators()` in `openjdk/mmtkUpcalls.cpp:56`.

**Comment by wks** [comment]
@k-sareen I later found (see my previous post) that it is not just the first mutator that is added twice, but other mutators are, too.  As we found that the root cause is the race between two threads (the VM Thread and the MMTk Coordinator thread).  I already encountered cases where all mutator threads are visited by both the VM Thread and the MMTk Coordinator thread before mmtk-core starts scanning any stack.

I grepped the vanilla OpenJDK code, and found that the `SafepointSynchronize::begin()` function is only ever called by the "VM Thread" (I mean there is a thread in OpenJDK named "VM Thread").  So we need to figure out whether it is legal at all to call `SafepointSynchronize::begin()` from other threads.  One obvious way is to look at how existing STW GC algorithms in OpenJDK stop the world.

**Comment by wks** [comment]
@k-sareen I later found (see my previous post) that it is not just the first mutator that is added twice, but other mutators are, too.  As we found that the root cause is the race between two threads (the VM Thread and the MMTk Coordinator thread).  I already encountered cases where all mutator threads are visited by both the VM Thread and the MMTk Coordinator thread before mmtk-core starts scanning any stack.

I grepped the vanilla OpenJDK code, and found that the `SafepointSynchronize::begin()` function is only ever called by the "VM Thread" (I mean there is a thread in OpenJDK named "VM Thread").  So we need to figure out whether it is legal at all to call `SafepointSynchronize::begin()` from other threads.  One obvious way is to look at how existing STW GC algorithms in OpenJDK stop the world.

**Comment by k-sareen** [comment]
Maybe we should migrate this bug to mmtk-openjdk?

**Comment by wks** [comment]
@k-sareen From what I found out yesterday, yes. It is a bug of the OpenJDK binding.
