### ISSUE TITLE
Graphchi deadlocks with GenImmix Issue

### ISSUE THREAD

**Issue by clairexhuang** [mmtk/mmtk-core#529]
On the running scripts, graphchi when running GenImmix using a sudo wrapper for CPU shielding runs into this issue. The previous invocation passed in 36711ms.

`graphchi 6000 1536 0ab1aTraceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1535, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.6/subprocess.py", line 891, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['sudo', '-E', 'cset', 'shield', '--user', 'claireh', '--group', 'claireh', '--exec', '--', '/home/claireh/mmtk-o
penjdk/repos/openjdk/build_barrier/linux-x86_64-normal-server-release/jdk/bin/java', '-XX:MetaspaceSize=500M', '-XX:+DisableExplicitGC', '-server', '
-XX:-TieredCompilation', '-Xcomp', '-XX:+UseThirdPartyHeap', '-Djava.library.path=/home/claireh/probes', '-Dprobes=RustMMTk', '-Xms1536M', '-Xmx1536M
', '-cp', '/usr/share/benchmarks/dacapo/dacapo-evaluation-git-29a657f.jar:/home/claireh/probes:/home/claireh/probes/probes.jar', 'Harness', '-c', 'pr
obe.DacapoChopinCallback', '-n', '5', '-s', 'default', 'graphchi']' timed out after 2400 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/claireh/.local/bin/running", line 11, in <module>
    load_entry_point('running-ng', 'console_scripts', 'running')()
  File "/home/claireh/running-ng/running/__main__.py", line 45, in main
    if m.run(args):
  File "/home/claireh/running-ng/running/command/runbms.py", line 413, in run
    run_hfacs(slice)
  File "/home/claireh/running-ng/running/command/runbms.py", line 405, in run_hfacs
    configs, runbms_dir, log_dir)
  File "/home/claireh/running-ng/running/command/runbms.py", line 303, in run_one_hfac
    configs, runbms_dir, log_dir)
  File "/home/claireh/running-ng/running/command/runbms.py", line 250, in run_one_benchmark
    c, bm, runbms_dir, size, fd
  File "/home/claireh/running-ng/running/command/runbms.py", line 121, in run_benchmark_with_config
    output, exit_status = mod_b.run(runtime, cwd=runbms_dir)
  File "/home/claireh/running-ng/running/benchmark.py", line 88, in run
    cwd=cwd
  File "/usr/lib/python3.6/subprocess.py", line 427, in run
    process.kill()
  File "/usr/lib/python3.6/subprocess.py", line 1610, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.6/subprocess.py", line 1600, in send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 1] Operation not permitted`

**Comment by KipHamiltons** [comment]
I had the same issue using `GenCopy`.
Running `./build/linux-x86_64-normal-server-$DEBUG_LEVEL/jdk/bin/java -XX:+UseThirdPartyHeap -jar /usr/share/benchmarks/dacapo/dacapo-evaluation-git-f480064.jar graphchi` with `DEBUG_LEVEL=slowdebug`, it non-deterministically stops completely, usually after at least a few hundred lines of output saying `nursery: Triggering collection` and `End of GC`.
Interestingly, I wasn't able to reproduce it in `release` after approx 20 attempts (it was around 50% of the time on `slowdebug`)
